trigger: none

pool: Mera Poll

jobs:
-   job: 
    displayName: Install npn and node 
    steps:
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '6'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'npm install'
        workingDirectory: '$(System.DefaultWorkingDirectory)/ReactTodoUIMonolith-main'
    
-   job:  
-   job: 
      
    