trigger: none
pool: Mera pool

stages:
  - stage:
    jobs:
      - job: build
        displayName: building application
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm install'
            workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main'

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm run build'
            workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main/build'
            ArtifactName: 'ReactTodoUI'
            publishLocation: 'Container'


# stages:
#   - stage:
#     jobs:
#       - deployment: ReactJS UI Deployment
#         environment: 
#           name: tst
#           resourceName: virtualMachine
#         strategy: 
#           runOnce:
#             deploy:
#               steps:
              
        
          