trigger: none


stages:
  - stage:  
    jobs:
      - job: build
        pool: Mera pool
        displayName: building application
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm install'
            workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main'

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm run build'
            workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main/build'
            ArtifactName: 'ReactTodoUI'
            publishLocation: 'Container'
  - stage: 
    jobs:
      - deployment: 
        environment: 
          name: Saurav-tst
        strategy: 
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'ReactTodoUI'
                  targetPath: '$(Pipeline.Workspace)'
        
          