trigger: none
pool: Mera pool
stages:
  - stage: stage1
    displayName: stage1
    jobs:
      - job: build
        displayName: building application
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm install'
            workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main'

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'npm run build'
            workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/ReactTodoUIMonolith-main/build'
            ArtifactName: 'ReactTodoUI'
            publishLocation: 'Container'

  - stage: stage2
    displayName: stage2
    dependsOn: stage1
    jobs:
      - deployment:
        environment: 
          name: Saurav-tst
          resourceType: virtualMachine
        strategy: 
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'ReactTodoUI'
                  targetPath: '$(Pipeline.Workspace)'
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |
                    sudo rm -rf  /var/www/html/*
                    sudo cp $(Pipeline.Workspace)/ReactTodoUI/* /var/www/html
              
